### ISSUE TITLE
unterminated character set at position 6

### ISSUE THREAD

**Issue by lepinekong** [wting/autojump#522] opened 2018-02-17 15:44 UTC
Hi, got this error when typing j somedir on Windows 10

> File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 523, in _parse
>   source.tell() - here)
>sre_constants.error: unterminated character set at position 6
>ECHO is off.

**Comment by wting** [comment] 2018-09-07 01:08
Closing as dupe of #543.

**Closed by wting** 2018-09-07 01:08 UTC
