### ISSUE TITLE
increasing the size of autojump's memory?

### ISSUE THREAD

**Issue by dfaure-kdab** [wting/autojump#527] opened 2018-04-05 15:14 UTC
I assume autojump uses a LRU data structure internally with a maximum size? Or does it grow to infinity?

In the first case, where can I see and adjust the size of autojump's memory?

My actual problem is that it keeps forgetting directories that I went to. But I don't know yet if it's a bug (related to the zsh integration, probably?) or if it's just that I navigate to very many directories so it forgets the "old" ones.

**Comment by wting** [comment] 2018-04-24 04:02
It grows infinitely. Try this out:

```shell
$ j -s | grep number
$ autojump --add /random_entry
$ j -s | grep number
```

The number of entries should increase by 1 after manually adding an new entry.

**Comment by wting** [comment] 2018-09-07 00:58
The DB has a race condition that leads to it getting wiped out. 😞 

Marking as a dupe of #391.

**Closed by wting** 2018-09-07 00:58 UTC
