### ISSUE TITLE
jump can't find the right path directly

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [wting/autojump#525] opened 2018-04-03 10:25 UTC
I installed autojump on Ubuntu 16.04 LTS,put  . /usr/share/autojump/autojump.sh  into the .bashrc. After source the .bashrc file,I get this situation:
$ cd Desktop/
$ cd ..
$ j D__
D__1__/home/moon/Desktop    D__2__/home/moon/Desktop

I used tab key.
@nicoulaj @KenMacD @blueyed @junkblocker @marktran

**Comment by Karmaki** [comment] 2018-08-02 07:24
I think that is a duplicate of #348.

**Comment by wting** [comment] 2018-09-07 01:01
Closing as dupe of #348.

**Closed by wting** 2018-09-07 01:01 UTC
