### ISSUE TITLE
autojump periodically delete its database

### ISSUE THREAD

**Issue by mrbig033** [wting/autojump#531] opened 2018-04-20 00:19 UTC
### My environment:
- [bash dotfiles](https://gitlab.com/mrbig/dotfiles/tree/master/bash)
- [.tmux.conf](https://gitlab.com/mrbig/dotfiles/blob/master/.tmux.conf)
- autojump v22.5.0
- xfce4-terminal 0.8.3 (Xfce 4.12)
- MX-Linux 17
### The problem:
- `autojump` deletes its database on `~/.local/share/autojump/autojump.txt`  about once per day. This might involve Tmux, but I'm not sure. The problem is solved with `cat autojump.txt.bak >> autojump.txt'`, but it's annoying nevertheless.

**Comment by sergiomb2** [comment] 2018-05-02 14:57
today 
```
-rw-------  1 sergio sergio 33215 abr  7 03:24 autojump.txt.backup29
-rw-------  1 sergio sergio   724 mai  1 22:11 autojump.txt.bak
-rw-------  1 sergio sergio   897 mai  2 15:45 autojump.txt
```
autojump.txt backup was cleaned , maybe one solution to mitigate this old problem is save backups every day , I don't understand when or how autojump is cleaned seems a problem of concurrency , but since 2016 I have this problem .

**Comment by mrbig033** [comment] 2018-05-08 02:36
Thank you for answering. I started using [fasd](https://github.com/clvv/fasd) because of this bug. It has more options and doesn't present this problem. I was even able to import my autojump database.

**Comment by wting** [comment] 2018-09-06 05:42
Yeah this is one of the most important bugs that I need to fix. 😢 

I'm glad you were able to import autojump database into fasd.

Closing as a dupe of #391

**Closed by wting** 2018-09-06 05:42 UTC
