### ISSUE TITLE
Autocomplete entries show up twice or more

### ISSUE THREAD

**Issue by sparkbuzz** [wting/autojump#521] opened 2018-02-16 05:19 UTC
When I use `j` to auto complete, I often see multiple duplicated entries in bash, is there a way I can fix this? Here's some example output. I replaced the text below but you'll get the idea, one of the directories, shows up 3 times.

```
sparky at the-machine in ~
$ j helloworld
helloworld__1__/Users/sparky/Projects/helloworld <--
helloworld__2__/Users/sparky/Projects/helloworld <--
helloworld__3__/Users/sparky/Projects/helloworld/something/else
helloworld__4__/Users/sparky/Projects/helloworld/something
helloworld__5__/Users/sparky/Projects/helloworld <--
helloworld__6__/Users/sparky/Projects/helloworld/one
helloworld__7__/Users/sparky/Projects/helloworld/two
helloworld__8__/Users/sparky/Projects/helloworld/three
helloworld__9__/Users/sparky/Projects/helloworld/four
```
I'm using bash 4.4.12 on macOS High Sierra (10.13.2)

Note: When I run `j -s` there are no duplicates in the output.

**Comment by wting** [comment] 2018-09-07 01:08
Closing as dupe of #348.

**Closed by wting** 2018-09-07 01:08 UTC
