### ISSUE TITLE
After reinstall no post install

### ISSUE THREAD

**Issue by lil5** [wting/autojump#517] opened 2018-01-25 12:10 UTC
```shell
$ sudo apt-get purge autojump
$ rm -r ~/.jump
$ sudo apt-get install autojump
$ autojump -v
autojump v22.2.4
$ j
j: command not found
$ autojump
Please source the correct autojump file in your shell's
startup file. For more information, please reinstall autojump
and read the post installation instructions.
```

How do I find the proper command to add to my `~/.bashrc`?

**Comment by shri3k** [comment] 2018-03-31 15:41
@lil5 Yea, it's a little misleading that msg but you'd need to add this

```shell
. /usr/share/autojump/autojump.sh
```
in your `.bashrc`.

The readme is actually in the following file which is hinted in [readme](https://github.com/wting/autojump#linux):
```shell
cat /usr/share/doc/autojump/README.Debian
```
Hope that helps.

**Comment by wting** [comment] 2018-09-07 01:11
Closing as dupe of #323.

**Closed by wting** 2018-09-07 01:11 UTC
